### ISSUE TITLE
top channels displaying logged in user also

### ISSUE THREAD

**Issue by CreedTech** [CreedTech/cr8iveshare#3]
`  

  # content creator suggestion
    all_users = Account.objects.all()
    user_following_all = []

    new_suggestions_list = [x for x in list(
        all_users) if (x not in list(user_following_all))]
    current_user = Account.objects.filter(username=request.user.username)
    final_suggestions_list = [x for x in list(
        new_suggestions_list) if (x not in list(current_user))]
    random.shuffle(final_suggestions_list)`

**Comment by CreedTech** [comment]
@Code-Warlock

**Comment by Code-Warlock** [comment]
I'll check it when I'm home... Cool stuff sha
